# Generated by Django 5.1.6 on 2025-04-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goverment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shipping_fe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
