# Generated by Django 5.1.6 on 2025-04-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_goverment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goverment',
            new_name='Government',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.government'),
        ),
    ]
