# Generated by Django 5.1.6 on 2025-04-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_goverment_government_customerorder_government'),
    ]

    operations = [
        migrations.RenameField(
            model_name='government',
            old_name='shipping_fe',
            new_name='shipping_fee',
        ),
    ]
