# Generated by Django 5.1.6 on 2025-04-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
