# Generated by Django 5.2 on 2025-04-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customerorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='user',
        ),
    ]
