# Generated by Django 5.2 on 2025-04-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderitem_product_code_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='product_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
