# Generated by Django 5.2 on 2025-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customerorder_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product_code',
        ),
    ]
