# Generated by Django 5.2 on 2025-04-07 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customerorder_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_code',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
