# Generated by Django 5.2 on 2025-04-07 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_orderitem_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
