# Generated by Django 5.2 on 2025-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderitem_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_code',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product_codes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
