# Generated by Django 5.2 on 2025-04-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_customerorder_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product_codes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
