# Generated by Django 5.2 on 2025-04-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
