# Generated by Django 5.2 on 2025-04-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_orderitem_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customerorder'),
        ),
    ]
