# Generated by Django 5.2 on 2025-04-08 08:59

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_images_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/'),
            preserve_default=False,
        ),
    ]
