# Generated by Django 5.2 on 2025-04-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='expiry_date',
            new_name='expire_date',
        ),
    ]
