# Generated by Django 5.2 on 2025-04-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_expiry_date_promocode_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
