# Generated by Django 5.2 on 2025-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_expire_date_promocode_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='min_order_value',
            field=models.FloatField(default=0, verbose_name='Minimum Order Value'),
        ),
    ]
