services:
  - type: web
    name: EcommerceStore
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput  # جمع ملفات static
    startCommand: daphne EcommerceStore.asgi:application  # تشغيل Daphne
    staticPublishPath: /static  # المسار الخاص بملفات static
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: EcommerceStore.settings.production  # تعيين إعدادات الإنتاج
      - key: DISABLE_COLLECTSTATIC
        value: "0"  # التأكد من تشغيل collectstatic
